# Generated by Django 4.2.2 on 2023-06-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtable',
            old_name='itemdecription',
            new_name='itemdescription',
        ),
    ]
