# Generated by Django 4.2.2 on 2023-06-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0002_rename_itemdecription_itemtable_itemdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='brand',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
