# Generated by Django 4.2.2 on 2023-06-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0003_itemtable_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='colour',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='seller',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='status',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
