# Generated by Django 4.2.2 on 2023-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.IntegerField()),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('password', models.CharField(max_length=25)),
                ('confirmpassword', models.CharField(max_length=25)),
            ],
        ),
    ]
