# Generated by Django 4.2.2 on 2023-06-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regtable',
            old_name='state',
            new_name='State',
        ),
    ]
